management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080
spring:
  rabbitmq:
    host: skunk.rmq.cloudamqp.com
    username: pohzgdvc
    password: I44lY3BxjhwiQMnzToRo_S0hfdiJW3U_
    virtual-host: pohzgdvc
  application:
    name: anmg-service
  boot:
    admin:
      client:
        password: admin
        url: http://localhost:8091/
        username: admin
  data:
    mongodb:
      uri: mongodb://heroku_l4vcg6kz:l318h0n4d5c8kb2vjra50682a8@ds213079.mlab.com:13079/heroku_l4vcg6kz?retryWrites=false
